name: Production Deployment

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Add AWS VM's host key to known hosts
        run: |
          mkdir -p ~/.ssh
          if [ -n "${{ secrets.VM_HOST_IP }}" ]; then
            ssh-keyscan -H ${{ secrets.VM_HOST_IP }} >> ~/.ssh/known_hosts
          else
            echo "VM_HOST_IP is not set!"
            exit 1
          fi

      - name: Copy code to AWS EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VM_HOST_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: .
          target: /home/${{ secrets.USERNAME }}/prod/backend

      - name: Copy env
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private-key.pem
          chmod 600 private-key.pem

          ssh -i private-key.pem ${{ secrets.USERNAME }}@${{ secrets.VM_HOST_IP }} -o StrictHostKeyChecking=no << 'ENDSSH'
            cd /home/${{ secrets.USERNAME }}/prod/backend
            touch .env
            cp /home/${{ secrets.USERNAME }}/env/prod/backend/.env /home/${{ secrets.USERNAME }}/prod/backend/.env
          ENDSSH

      - name: Deploy to AWS EC2
        run: |
          ssh -i private-key.pem ${{ secrets.USERNAME }}@${{ secrets.VM_HOST_IP }} -o StrictHostKeyChecking=no << 'ENDSSH'
              cd /home/${{ secrets.USERNAME }}/prod/backend
              sudo systemctl stop prod-backend
              docker build --no-cache -t prod-backend .
              docker images -a
      
              # Remove the old container if it exists
              docker rm -f my-prod-backend || true
      
              # Run the new Docker container
              docker run --name my-prod-backend -d -p 3000:3000 prod-backend:latest
      
              docker ps -a
              echo "Prod deployment complete"
          ENDSSH
